Repository GEOS-DEV/thirdPartyLibs, pull requests merged in 2024-06, with the labels that each got.

#264 Build Geos against TPLs with ENABLE_CUDA=OFF on pangea3
  CMakeLists.txt
  host-configs/TOTAL/pangea3-gcc8.4.1-openmpi-4.1.2.cmake
Labels: bug, flag: ready to be merged, flag: ready for review

#258 remove RESQML support from tpls
  CMakeLists.txt
  tplMirror/Minizip-1.1_cmake0.1.tar.gz
  tplMirror/boost_1_67_0.tar.gz
  tplMirror/fesapi-2.4.0.0.tar.gz
Labels: enhancement, flag: ready for review

#262 Add Pangea4 host configs
  host-configs/TOTAL/pangea4-base.cmake
  host-configs/TOTAL/pangea4-gcc12.1-hpcxompi2.17.1-onemkl2023.2.0.cmake
  host-configs/TOTAL/pangea4-gcc12.1-hpcxompi2.17.1-openblas0.3.23.cmake
  host-configs/TOTAL/pangea4-gcc12.1-openmpi4.1.6-onemkl2023.2.0.cmake
  host-configs/TOTAL/pangea4-gcc12.1-openmpi4.1.6-openblas0.3.23.cmake
Labels: enhancement
